- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs
   
- name: Copying mongo repos to install mongod client Server
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongod client Server
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: check products loaded or not
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  # ignore_errors: true
  # ignore_unreachable: true

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  # ignore_errors: true
  # ignore_unreachable: true

- name: load products
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  # ignore_errors: true
  # ignore_unreachable: true

- name: "restarting {{ component }}"
  include_role:
    name: common
    tasks_from: systemd